### ISSUE TITLE
Add main character

### ISSUE THREAD

**Issue by MkKorhonen** [kiigame/kged#40]
As a user,
i want to add my character to the game,
so i don't have to use the default character.

Implementation proposal

Make a new option where you can add 4 pictures of main character for two main animations (character speak and character idle)

**Comment by evktalo** [comment]
This would be nice. Idle and monologue animations are referenced by the engine directly, and those should exist always. I think the number of frames is arbitrary though. Even 1 is enough (or should be).

The panic animation is not referenced in the engine itself, it's an example of an animation that can be defined to be played in interactions.

So this ticket could be sliced to changing default animations (idle and speak) and the possibility of adding additional animations.
