### ISSUE TITLE
Listing of stuff (rooms, items etc.) alphabetical sorting works unexpectedly.

### ISSUE THREAD

**Issue by Svenskapojkarna** [kiigame/kged#8]
When creating rooms, items or furnitures, the list is sorted alpabetically. The sorting works in a way, that first are names starting in capital letter and then the ones starting in small letter. I'm not sure if this is the way it is suppose to work, but it seemed unexpected to me.

![kuva](https://user-images.githubusercontent.com/36008914/74166646-9712ff80-4c2f-11ea-83cb-a9df9cde5d7b.png)

**Comment by evktalo** [comment]
Yup, disregarding case for alphabetical sorting would make sense from user point of view.

**Comment by evktalo** [comment]
Fixed in #39
